# Generated by Django 3.0.4 on 2020-04-09 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20200409_1654'),
        ('orders', '0002_auto_20200409_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='carts.Cart'),
            preserve_default=False,
        ),
    ]
