# Generated by Django 3.0.4 on 2020-04-09 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20200409_1654'),
        ('orders', '0003_auto_20200409_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='carts.CartItem'),
        ),
    ]
