# Generated by Django 3.0.4 on 2020-03-29 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0002_auto_20200329_1538'),
        ('product_items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carts.Cart')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='product_items.ProductItem')),
            ],
        ),
    ]
