# Generated by Django 3.0.4 on 2020-03-29 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_items', '0001_initial'),
        ('cart_items', '0002_auto_20200329_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product_items.ProductItem'),
        ),
    ]
